# general settings
name: train_DiffIRS1_x2
model_type: DiffIRS1Model
scale: 2
num_gpu: auto  # auto: can infer from your visible devices automatically. official: 4 GPUs
manual_seed: 0

gt_size: 256
# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /root/datasets/DF2K
    dataroot_lq: /root/datasets/DF2K/LR_bicubic_sub/X2
    meta_info_file: datasets/meta_info/meta_info_DF2K_sub_pair.txt
    # (for lmdb)
    # dataroot_gt: datasets/DIV2K/DIV2K_train_HR_sub.lmdb
    # dataroot_lq: datasets/DIV2K/DIV2K_train_LR_bicubic_X2_sub.lmdb
    filename_tmpl: '{}'
    io_backend:
      type: disk
      # (for lmdb)
      # type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 9
    dataset_enlarge_ratio: 100
    prefetch_mode: ~

  # Uncomment these for validation
  val_1:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /root/datasets/benchmark/Urban100/HR
    dataroot_lq: /root/datasets/benchmark/Urban100/LRx2
    # filename_tmpl: '{}x4'
    io_backend:
      type: disk
  
  val_2:
    name: DIV2K100
    type: PairedImageDataset
    dataroot_gt: /root/datasets/benchmark/DIV2K100/HR
    dataroot_lq: /root/datasets/benchmark/DIV2K100/LRx2
    io_backend:
      type: disk

# network structures
network_g:
  type: DiffIRS1
  n_encoder_res: 9
  inp_channels: 3
  out_channels: 3
  scale: 2
  dim: 64
  num_blocks: [13,1,1,1]
  num_refinement_blocks: 13
  heads: [1,2,4,8]
  ffn_expansion_factor: 2.2
  bias: False
  LayerNorm_type: BiasFree

# path
path:
  pretrain_network_g: ~
  param_key_g: params_ema
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999

  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [500000,700000]
    gamma: 0.5

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# Uncomment these for validation
# validation settings
val:
  window_size: 8
  val_freq: !!float 5e3
  save_img: False

  metrics:
    psnr: # metric name
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true

# logging settings
logger:
  print_freq: 1000
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
